/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AIRateInquiryRequest { 
    weight?: number;
    serviceType?: string | null;
    origin?: string | null;
    destination?: string | null;
}

