/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BsonValue } from './bson-value';


export interface BsonElement { 
    name?: string | null;
    value?: BsonValue;
}

