/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BsonMinKey } from './bson-min-key';
import { ObjectId } from './object-id';
import { BsonRegularExpression } from './bson-regular-expression';
import { BsonJavaScript } from './bson-java-script';
import { BsonTimestamp } from './bson-timestamp';
import { BsonType } from './bson-type';
import { BsonElement } from './bson-element';
import { BsonSymbol } from './bson-symbol';
import { Regex } from './regex';
import { BsonDateTime } from './bson-date-time';
import { BsonMaxKey } from './bson-max-key';
import { BsonJavaScriptWithScope } from './bson-java-script-with-scope';
import { BsonBinaryData } from './bson-binary-data';
import { BsonUndefined } from './bson-undefined';
import { BsonValue } from './bson-value';


export interface BsonNull { 
    readonly asBoolean?: boolean;
    readonly asBsonArray?: Array<BsonValue> | null;
    asBsonBinaryData?: BsonBinaryData;
    asBsonDateTime?: BsonDateTime;
    readonly asBsonDocument?: Array<BsonElement> | null;
    asBsonJavaScript?: BsonJavaScript;
    asBsonJavaScriptWithScope?: BsonJavaScriptWithScope;
    asBsonMaxKey?: BsonMaxKey;
    asBsonMinKey?: BsonMinKey;
    asBsonNull?: BsonNull;
    asBsonRegularExpression?: BsonRegularExpression;
    asBsonSymbol?: BsonSymbol;
    asBsonTimestamp?: BsonTimestamp;
    asBsonUndefined?: BsonUndefined;
    asBsonValue?: BsonValue;
    readonly asByteArray?: string | null;
    readonly asDecimal?: number;
    asDecimal128?: object;
    readonly asDouble?: number;
    readonly asGuid?: string;
    readonly asInt32?: number;
    readonly asInt64?: number;
    readonly asLocalTime?: string;
    readonly asNullableBoolean?: boolean | null;
    readonly asNullableDecimal?: number | null;
    asNullableDecimal128?: object;
    readonly asNullableDouble?: number | null;
    readonly asNullableGuid?: string | null;
    readonly asNullableInt32?: number | null;
    readonly asNullableInt64?: number | null;
    readonly asNullableLocalTime?: string | null;
    asNullableObjectId?: ObjectId;
    readonly asNullableUniversalTime?: string | null;
    asObjectId?: ObjectId;
    asRegex?: Regex;
    readonly asString?: string | null;
    readonly asUniversalTime?: string;
    readonly isBoolean?: boolean;
    readonly isBsonArray?: boolean;
    readonly isBsonBinaryData?: boolean;
    readonly isBsonDateTime?: boolean;
    readonly isBsonDocument?: boolean;
    readonly isBsonJavaScript?: boolean;
    readonly isBsonJavaScriptWithScope?: boolean;
    readonly isBsonMaxKey?: boolean;
    readonly isBsonMinKey?: boolean;
    readonly isBsonNull?: boolean;
    readonly isBsonRegularExpression?: boolean;
    readonly isBsonSymbol?: boolean;
    readonly isBsonTimestamp?: boolean;
    readonly isBsonUndefined?: boolean;
    readonly isDecimal128?: boolean;
    readonly isDouble?: boolean;
    readonly isGuid?: boolean;
    readonly isInt32?: boolean;
    readonly isInt64?: boolean;
    readonly isNumeric?: boolean;
    readonly isObjectId?: boolean;
    readonly isString?: boolean;
    readonly isValidDateTime?: boolean;
    bsonType?: BsonType;
}
export namespace BsonNull {
}


