/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyProfileRequest { 
    organizationName?: string | null;
    corporateWebsite?: string | null;
    primaryLanguage?: string | null;
    description?: string | null;
    supportEmail?: string | null;
    supportPhone?: string | null;
    headquartersAddress?: string | null;
}

