/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePaymentRequest { 
    trackingNumber?: string | null;
    amount?: number;
    method?: string | null;
    transactionId?: string | null;
}

