/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRateRequest { 
    serviceType?: string | null;
    baseRate?: number;
    additionalKgRate?: number;
    minWeight?: number;
    maxWeight?: number;
}

