/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParcelInfo } from './parcelInfo';
import { ContactInfo } from './contactInfo';


export interface CreateShipmentRequest { 
    sender?: ContactInfo;
    receiver?: ContactInfo;
    parcel?: ParcelInfo;
    serviceType?: string | null;
    specialInstructions?: string | null;
}

