/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateComplaintRequest { 
    trackingNumber?: string | null;
    type?: string | null;
    description?: string | null;
    customerEmail?: string | null;
    customerPhone?: string | null;
}

