/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateRateRequest } from './create-rate-request';


export interface OnboardingRatesRequest { 
    rates?: Array<CreateRateRequest> | null;
}

