/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OnboardingStatus } from './onboarding-status';


export interface OnboardingResponse { 
    tenantId?: string | null;
    tenantName?: string | null;
    apiKey?: string | null;
    plan?: string | null;
    role?: string | null;
    message?: string | null;
    onboarding?: OnboardingStatus;
}

