/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParcelInfo { 
    weight?: number;
    length?: number | null;
    width?: number | null;
    height?: number | null;
    description?: string | null;
    value?: number | null;
}

