/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegexOptions } from './regex-options';


export interface Regex { 
    options?: RegexOptions;
    readonly rightToLeft?: boolean;
    readonly matchTimeout?: string;
}
export namespace Regex {
}


