/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionResponse } from './session-response';


export interface SessionListResponse { 
    sessions?: Array<SessionResponse> | null;
    total?: number;
}

