/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BsonElement } from './bson-element';


export interface SessionResponse { 
    sessionId?: string | null;
    userId?: string | null;
    channel?: string | null;
    data?: Array<BsonElement> | null;
    createdAt?: string;
    updatedAt?: string;
    expiresAt?: string;
    isActive?: boolean;
}

