/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetupTelegramRequest { 
    botToken?: string | null;
    botUsername?: string | null;
    allowedCommands?: Array<string> | null;
    autoReplyEnabled?: boolean;
    forwardToBrain?: boolean;
    greetingMessage?: string | null;
}

