/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantBrandingRequest } from './tenantBrandingRequest';


export interface SetupTenantRequest { 
    companyName?: string | null;
    plan?: string | null;
    enabledServices?: Array<string> | null;
    branding?: TenantBrandingRequest;
}

