/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramChat { 
    id?: number;
    type?: string | null;
    title?: string | null;
    username?: string | null;
    firstName?: string | null;
    lastName?: string | null;
}

