/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramChatResponse } from './telegram-chat-response';


export interface TelegramChatListResponse { 
    chats?: Array<TelegramChatResponse> | null;
    total?: number;
    skip?: number;
    limit?: number;
}

