/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramUser { 
    id?: number;
    is_bot?: boolean;
    first_name?: string | null;
    last_name?: string | null;
    username?: string | null;
    language_code?: string | null;
}

