/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramConfigDto } from './telegramConfigDto';


export interface TelegramIntegrationResponse { 
    id?: string | null;
    integrationType?: string | null;
    isActive?: boolean;
    config?: TelegramConfigDto;
    createdAt?: string;
    updatedAt?: string;
}

