/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramWebhookInfo { 
    url?: string | null;
    hasCustomCertificate?: boolean;
    pendingUpdateCount?: number;
    lastErrorMessage?: string | null;
    lastErrorDate?: number | null;
}

