/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramUser } from './telegramUser';
import { TelegramChat } from './telegramChat';


export interface TelegramMessage { 
    message_id?: number;
    from?: TelegramUser;
    chat?: TelegramChat;
    text?: string | null;
    date?: number;
}

