/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramMessageResponse { 
    messageId?: string | null;
    chatId?: string | null;
    fromUser?: string | null;
    text?: string | null;
    direction?: string | null;
    timestamp?: string;
    sessionId?: string | null;
}

