/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramMessage } from './telegram-message';
import { TelegramUser } from './telegram-user';


export interface TelegramCallbackQuery { 
    id?: string | null;
    from?: TelegramUser;
    message?: TelegramMessage;
    data?: string | null;
}

