/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramMessageResponse } from './telegram-message-response';


export interface TelegramMessageListResponse { 
    messages?: Array<TelegramMessageResponse> | null;
    total?: number;
    skip?: number;
    limit?: number;
}

