/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramMessage } from './telegram-message';
import { TelegramCallbackQuery } from './telegram-callback-query';


export interface TelegramUpdate { 
    updateId?: number;
    message?: TelegramMessage;
    callbackQuery?: TelegramCallbackQuery;
}

