/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelegramMessage } from './telegramMessage';
import { TelegramCallbackQuery } from './telegramCallbackQuery';


export interface TelegramUpdate { 
    update_id?: number;
    message?: TelegramMessage;
    callback_query?: TelegramCallbackQuery;
}

