/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramChatResponse { 
    chatId?: string | null;
    userName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    createdAt?: string;
    lastMessageAt?: string | null;
    messageCount?: number;
}

