/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelegramUser { 
    id?: number;
    isBot?: boolean;
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    languageCode?: string | null;
}

