/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TenantResponse { 
    id?: string | null;
    name?: string | null;
    apiKey?: string | null;
    plan?: string | null;
    createdAt?: string;
}

