/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TenantUserResponse { 
    id?: string | null;
    auth0UserId?: string | null;
    tenantId?: string | null;
    email?: string | null;
    name?: string | null;
    role?: string | null;
    status?: string | null;
    invitedAt?: string | null;
    invitedBy?: string | null;
    createdAt?: string;
}

