/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BsonElement } from './bsonElement';


export interface UpdateSessionDataRequest { 
    data?: Array<BsonElement> | null;
}

