/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRateRequest { 
    baseRate?: number | null;
    additionalKgRate?: number | null;
    minWeight?: number | null;
    maxWeight?: number | null;
}

