/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AICreateShipmentRequest } from '../model/models';
import { AIFileComplaintRequest } from '../model/models';
import { AIRateInquiryRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AIBrainServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/ai/complaints/file
     * @param aIFileComplaintRequest 
     */
    apiAiComplaintsFilePost(aIFileComplaintRequest?: AIFileComplaintRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/ai/customers/{phoneOrEmail}
     * @param phoneOrEmail 
     */
    apiAiCustomersPhoneOrEmailGet(phoneOrEmail: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/ai/rates/inquiry
     * @param aIRateInquiryRequest 
     */
    apiAiRatesInquiryPost(aIRateInquiryRequest?: AIRateInquiryRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/ai/shipments/create
     * @param aICreateShipmentRequest 
     */
    apiAiShipmentsCreatePost(aICreateShipmentRequest?: AICreateShipmentRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/ai/shipments/tracking/{trackingNumber}
     * @param trackingNumber 
     */
    apiAiShipmentsTrackingTrackingNumberGet(trackingNumber: string, extraHttpRequestParams?: any): Observable<{}>;

}
