export * from './aIBrain.service';
import { AIBrainService } from './aIBrain.service';
export * from './aIBrain.serviceInterface';
export * from './complaints.service';
import { ComplaintsService } from './complaints.service';
export * from './complaints.serviceInterface';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './dashboard.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './integrations.service';
import { IntegrationsService } from './integrations.service';
export * from './integrations.serviceInterface';
export * from './onboarding.service';
import { OnboardingService } from './onboarding.service';
export * from './onboarding.serviceInterface';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './payments.serviceInterface';
export * from './rates.service';
import { RatesService } from './rates.service';
export * from './rates.serviceInterface';
export * from './sessions.service';
import { SessionsService } from './sessions.service';
export * from './sessions.serviceInterface';
export * from './shipments.service';
import { ShipmentsService } from './shipments.service';
export * from './shipments.serviceInterface';
export * from './telegram.service';
import { TelegramService } from './telegram.service';
export * from './telegram.serviceInterface';
export * from './tenantUsers.service';
import { TenantUsersService } from './tenantUsers.service';
export * from './tenantUsers.serviceInterface';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './tenants.serviceInterface';
export const APIS = [AIBrainService, ComplaintsService, DashboardService, HealthService, IntegrationsService, OnboardingService, PaymentsService, RatesService, SessionsService, ShipmentsService, TelegramService, TenantUsersService, TenantsService];
