export * from './ai-brain.service';
import { AIBrainService } from './ai-brain.service';
export * from './complaints.service';
import { ComplaintsService } from './complaints.service';
export * from './core-courier-service-api.service';
import { CoreCourierServiceApiService } from './core-courier-service-api.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './integrations.service';
import { IntegrationsService } from './integrations.service';
export * from './onboarding.service';
import { OnboardingService } from './onboarding.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './rates.service';
import { RatesService } from './rates.service';
export * from './sessions.service';
import { SessionsService } from './sessions.service';
export * from './shipments.service';
import { ShipmentsService } from './shipments.service';
export * from './telegram.service';
import { TelegramService } from './telegram.service';
export * from './tenant-users.service';
import { TenantUsersService } from './tenant-users.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './weather-forecast.service';
import { WeatherForecastService } from './weather-forecast.service';
export const APIS = [AIBrainService, ComplaintsService, CoreCourierServiceApiService, DashboardService, HealthService, IntegrationsService, OnboardingService, PaymentsService, RatesService, SessionsService, ShipmentsService, TelegramService, TenantUsersService, TenantsService, WeatherForecastService];
