/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateComplaintRequest } from '../model/models';
import { UpdateComplaintRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ComplaintsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/complaints/{complaintId}
     * @param complaintId 
     */
    apiComplaintsComplaintIdGet(complaintId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/complaints/{complaintId}
     * @param complaintId 
     * @param updateComplaintRequest 
     */
    apiComplaintsComplaintIdPatch(complaintId: string, updateComplaintRequest?: UpdateComplaintRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/complaints
     * @param status 
     * @param type 
     * @param page 
     * @param pageSize 
     */
    apiComplaintsGet(status?: string, type?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/complaints
     * @param createComplaintRequest 
     */
    apiComplaintsPost(createComplaintRequest?: CreateComplaintRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/complaints/shipment/{trackingNumber}
     * @param trackingNumber 
     */
    apiComplaintsShipmentTrackingNumberGet(trackingNumber: string, extraHttpRequestParams?: any): Observable<{}>;

}
