/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/dashboard/complaints/stats
     * @param period 
     */
    apiDashboardComplaintsStatsGet(period?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/dashboard/overview
     */
    apiDashboardOverviewGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/dashboard/revenue/stats
     * @param period 
     */
    apiDashboardRevenueStatsGet(period?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/dashboard/shipments/stats
     * @param period 
     */
    apiDashboardShipmentsStatsGet(period?: string, extraHttpRequestParams?: any): Observable<{}>;

}
