/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SetupTelegramRequest } from '../model/models';
import { TelegramIntegrationResponse } from '../model/models';
import { TelegramStatusResponse } from '../model/models';
import { TelegramWebhookInfo } from '../model/models';
import { TestConnectionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface IntegrationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/integrations/telegram/disconnect
     */
    apiIntegrationsTelegramDisconnectDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/integrations/telegram/setup
     * @param setupTelegramRequest 
     */
    apiIntegrationsTelegramSetupPost(setupTelegramRequest?: SetupTelegramRequest, extraHttpRequestParams?: any): Observable<TelegramIntegrationResponse>;

    /**
     * 
     * 
     * @endpoint get /api/integrations/telegram/status
     */
    apiIntegrationsTelegramStatusGet(extraHttpRequestParams?: any): Observable<TelegramStatusResponse>;

    /**
     * 
     * 
     * @endpoint post /api/integrations/telegram/test-connection
     * @param testConnectionRequest 
     */
    apiIntegrationsTelegramTestConnectionPost(testConnectionRequest?: TestConnectionRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/integrations/telegram/webhook-info
     */
    apiIntegrationsTelegramWebhookInfoGet(extraHttpRequestParams?: any): Observable<TelegramWebhookInfo>;

    /**
     * 
     * 
     * @endpoint post /api/integrations/telegram/webhook/{tenantId}
     * @param tenantId 
     */
    apiIntegrationsTelegramWebhookTenantIdPost(tenantId: string, extraHttpRequestParams?: any): Observable<{}>;

}
