/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInviteRequest } from '../model/models';
import { OnboardingResponse } from '../model/models';
import { SetupTenantRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OnboardingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/onboarding/accept-invite
     * @param acceptInviteRequest 
     */
    apiOnboardingAcceptInvitePost(acceptInviteRequest?: AcceptInviteRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/onboarding/setup
     * @param setupTenantRequest 
     */
    apiOnboardingSetupPost(setupTenantRequest?: SetupTenantRequest, extraHttpRequestParams?: any): Observable<OnboardingResponse>;

}
