/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInviteRequest } from '../model/models';
import { CompanyProfileRequest } from '../model/models';
import { OnboardingRatesRequest } from '../model/models';
import { OnboardingResponse } from '../model/models';
import { OnboardingStatusResponse } from '../model/models';
import { SetupTenantRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OnboardingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/onboarding/accept-invite
     * @param acceptInviteRequest 
     */
    apiOnboardingAcceptInvitePost(acceptInviteRequest?: AcceptInviteRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/onboarding/company-profile
     * @param companyProfileRequest 
     */
    apiOnboardingCompanyProfilePut(companyProfileRequest?: CompanyProfileRequest, extraHttpRequestParams?: any): Observable<OnboardingStatusResponse>;

    /**
     * 
     * 
     * @endpoint post /api/onboarding/rates
     * @param onboardingRatesRequest 
     */
    apiOnboardingRatesPost(onboardingRatesRequest?: OnboardingRatesRequest, extraHttpRequestParams?: any): Observable<OnboardingStatusResponse>;

    /**
     * 
     * 
     * @endpoint post /api/onboarding/setup
     * @param setupTenantRequest 
     */
    apiOnboardingSetupPost(setupTenantRequest?: SetupTenantRequest, extraHttpRequestParams?: any): Observable<OnboardingResponse>;

    /**
     * 
     * 
     * @endpoint get /api/onboarding/status
     */
    apiOnboardingStatusGet(extraHttpRequestParams?: any): Observable<OnboardingStatusResponse>;

}
