/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePaymentRequest } from '../model/models';
import { UpdatePaymentStatusRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PaymentsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/payments
     * @param status 
     * @param page 
     * @param pageSize 
     */
    apiPaymentsGet(status?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/payments/{paymentId}
     * @param paymentId 
     */
    apiPaymentsPaymentIdGet(paymentId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/payments/{paymentId}/status
     * @param paymentId 
     * @param updatePaymentStatusRequest 
     */
    apiPaymentsPaymentIdStatusPatch(paymentId: string, updatePaymentStatusRequest?: UpdatePaymentStatusRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/payments
     * @param createPaymentRequest 
     */
    apiPaymentsPost(createPaymentRequest?: CreatePaymentRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/payments/shipment/{trackingNumber}
     * @param trackingNumber 
     */
    apiPaymentsShipmentTrackingNumberGet(trackingNumber: string, extraHttpRequestParams?: any): Observable<{}>;

}
