/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CalculateRateRequest } from '../model/models';
import { CreateRateRequest } from '../model/models';
import { UpdateRateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/rates/calculate
     * @param calculateRateRequest 
     */
    apiRatesCalculatePost(calculateRateRequest?: CalculateRateRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/rates
     */
    apiRatesGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/rates
     * @param createRateRequest 
     */
    apiRatesPost(createRateRequest?: CreateRateRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/rates/{rateId}
     * @param rateId 
     */
    apiRatesRateIdDelete(rateId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/rates/{rateId}
     * @param rateId 
     */
    apiRatesRateIdGet(rateId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/rates/{rateId}
     * @param rateId 
     * @param updateRateRequest 
     */
    apiRatesRateIdPatch(rateId: string, updateRateRequest?: UpdateRateRequest, extraHttpRequestParams?: any): Observable<{}>;

}
