/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSessionRequest } from '../model/models';
import { SessionListResponse } from '../model/models';
import { SessionResponse } from '../model/models';
import { UpdateSessionDataRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SessionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/sessions/cleanup
     */
    apiSessionsCleanupPost(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/sessions
     */
    apiSessionsGet(extraHttpRequestParams?: any): Observable<SessionListResponse>;

    /**
     * 
     * 
     * @endpoint post /api/sessions
     * @param createSessionRequest 
     */
    apiSessionsPost(createSessionRequest?: CreateSessionRequest, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/sessions/{sessionId}
     * @param sessionId 
     */
    apiSessionsSessionIdDelete(sessionId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/sessions/{sessionId}/extend
     * @param sessionId 
     * @param hours 
     */
    apiSessionsSessionIdExtendPost(sessionId: string, hours?: number, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/sessions/{sessionId}
     * @param sessionId 
     */
    apiSessionsSessionIdGet(sessionId: string, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * 
     * 
     * @endpoint put /api/sessions/{sessionId}
     * @param sessionId 
     * @param updateSessionDataRequest 
     */
    apiSessionsSessionIdPut(sessionId: string, updateSessionDataRequest?: UpdateSessionDataRequest, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/sessions/user/{userId}
     * @param userId 
     */
    apiSessionsUserUserIdDelete(userId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/sessions/user/{userId}
     * @param userId 
     */
    apiSessionsUserUserIdGet(userId: string, extraHttpRequestParams?: any): Observable<SessionListResponse>;

}
