/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateEventRequest } from '../model/models';
import { CreateShipmentRequest } from '../model/models';
import { ShipmentResponse } from '../model/models';
import { ShipmentResponsePagedResponse } from '../model/models';
import { UpdateStatusRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShipmentsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/shipments
     * @param page 
     * @param pageSize 
     * @param status 
     */
    apiShipmentsGet(page?: number, pageSize?: number, status?: string, extraHttpRequestParams?: any): Observable<ShipmentResponsePagedResponse>;

    /**
     * 
     * 
     * @endpoint post /api/shipments
     * @param createShipmentRequest 
     */
    apiShipmentsPost(createShipmentRequest?: CreateShipmentRequest, extraHttpRequestParams?: any): Observable<ShipmentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/shipments/{shipmentId}/status-history
     * @param shipmentId 
     */
    apiShipmentsShipmentIdStatusHistoryGet(shipmentId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/shipments/{trackingNumber}/events
     * @param trackingNumber 
     */
    apiShipmentsTrackingNumberEventsGet(trackingNumber: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/shipments/{trackingNumber}/events
     * @param trackingNumber 
     * @param createEventRequest 
     */
    apiShipmentsTrackingNumberEventsPost(trackingNumber: string, createEventRequest?: CreateEventRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/shipments/tracking/{trackingNumber}
     * @param trackingNumber 
     */
    apiShipmentsTrackingTrackingNumberGet(trackingNumber: string, extraHttpRequestParams?: any): Observable<ShipmentResponse>;

    /**
     * 
     * 
     * @endpoint patch /api/shipments/tracking/{trackingNumber}/status
     * @param trackingNumber 
     * @param updateStatusRequest 
     */
    apiShipmentsTrackingTrackingNumberStatusPatch(trackingNumber: string, updateStatusRequest?: UpdateStatusRequest, extraHttpRequestParams?: any): Observable<ShipmentResponse>;

}
