/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SendTelegramMessageRequest } from '../model/models';
import { TelegramChatListResponse } from '../model/models';
import { TelegramMessageListResponse } from '../model/models';
import { TelegramUpdate } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TelegramServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/telegram/chats/{chatId}/messages
     * @param chatId 
     * @param skip 
     * @param limit 
     */
    apiTelegramChatsChatIdMessagesGet(chatId: string, skip?: number, limit?: number, extraHttpRequestParams?: any): Observable<TelegramMessageListResponse>;

    /**
     * 
     * 
     * @endpoint get /api/telegram/chats
     * @param skip 
     * @param limit 
     */
    apiTelegramChatsGet(skip?: number, limit?: number, extraHttpRequestParams?: any): Observable<TelegramChatListResponse>;

    /**
     * 
     * 
     * @endpoint post /api/telegram/send
     * @param sendTelegramMessageRequest 
     */
    apiTelegramSendPost(sendTelegramMessageRequest?: SendTelegramMessageRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/telegram/webhook
     * @param telegramUpdate 
     */
    apiTelegramWebhookPost(telegramUpdate?: TelegramUpdate, extraHttpRequestParams?: any): Observable<{}>;

}
