/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTenantRequest } from '../model/models';
import { TenantResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TenantsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/tenants/{id}
     * @param id 
     */
    apiTenantsIdGet(id: string, extraHttpRequestParams?: any): Observable<TenantResponse>;

    /**
     * 
     * 
     * @endpoint post /api/tenants
     * @param createTenantRequest 
     */
    apiTenantsPost(createTenantRequest?: CreateTenantRequest, extraHttpRequestParams?: any): Observable<TenantResponse>;

}
