/**
 * CoreCourierService.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTenantUserRequest } from '../model/models';
import { InviteTenantUserRequest } from '../model/models';
import { TenantUserResponse } from '../model/models';
import { UpdateTenantUserRoleRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TenantUsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/tenant-users
     */
    apiTenantUsersGet(extraHttpRequestParams?: any): Observable<Array<TenantUserResponse>>;

    /**
     * 
     * 
     * @endpoint post /api/tenant-users/invite
     * @param inviteTenantUserRequest 
     */
    apiTenantUsersInvitePost(inviteTenantUserRequest?: InviteTenantUserRequest, extraHttpRequestParams?: any): Observable<TenantUserResponse>;

    /**
     * 
     * 
     * @endpoint post /api/tenant-users
     * @param createTenantUserRequest 
     */
    apiTenantUsersPost(createTenantUserRequest?: CreateTenantUserRequest, extraHttpRequestParams?: any): Observable<TenantUserResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/tenant-users/{tenantUserId}
     * @param tenantUserId 
     */
    apiTenantUsersTenantUserIdDelete(tenantUserId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/tenant-users/{tenantUserId}/role
     * @param tenantUserId 
     * @param updateTenantUserRoleRequest 
     */
    apiTenantUsersTenantUserIdRolePatch(tenantUserId: string, updateTenantUserRoleRequest?: UpdateTenantUserRoleRequest, extraHttpRequestParams?: any): Observable<{}>;

}
